###
GET https://api.github.com/search/code?q=user%3Ahipravin+OR+user%3Abclozel+immutable
Accept: application/vnd.github+json
Authorization: Bearer {{gh_token}}

###
GET https://api.github.com/search/code?q=user%3Abclozel+immutable
Accept: application/vnd.github.text-match+json
Authorization: Bearer {{gh_token}}

###
https://api.github.com/search/code?q=user%3Ahipravin+OR+user%3Abclozel+OR+user%3Ajosepaumard+immutable
Accept: application/vnd.github.text-match+json
Authorization: Bearer {{gh_token}}

###
https://api.github.com/search/code?q=user%3Ahipravin+OR+user%3Abclozel+OR+user%3Ajosepaumard+filename:Dockerfile+from
Accept: application/vnd.github.text-match+json
Authorization: Bearer {{gh_token}}

###
GET https://api.github.com/search/code?q=a
Accept: application/vnd.github.text-match+json
Authorization: Bearer {{gh_token}}